### ISSUE TITLE
Issue Portfolio 

### ISSUE THREAD

**Issue by AminaBuhari** [mrEckendonk/portfolio#16]
Hi Mike, 
Good job so far creating your portfolio, 👍
However there are some few changes you might like to add to render it functional and also to make the UX design match the figma design. 

- You can remove the background scroll when the pop-up (project details )  shows up so as to allow the user read the page better. You can achieve this using position fixed CSS property.
- To allow users navigate properly, you can link the contact nav bar with the contact form.
- The About section has some text alignment issues which doesn't match the figma design. 
- Each card show the same popup window. You can create a popup window dynamically using objects to fix that. 

Cheers and Happy Coding 🎉👏

**Comment by mrEckendonk** [comment]
Made the changes, closing the issue
