### ISSUE TITLE
Morning Peer Code Review

### ISSUE THREAD

**Issue by dodoburner** [mrEckendonk/portfolio#18]
The project looks really great it is almost perfect but there is still a bit room for improvement
- The contact link doesn't work for the desktop version
- The email button opens the mobile menu in the desktop version
- When resizing the window some images and text overlap
- In the about section the heading isn't alignent
- In the contact section the textarea tag doesn't expand as much as the other inputs
- The first project can use some more spacing in the mobile version

**Comment by mrEckendonk** [comment]
I am closing the issue and fixed the suggested improvements.
