### ISSUE TITLE
Morning session peer to peer code review

### ISSUE THREAD

**Issue by ghost** [mrEckendonk/portfolio#21]
Hey Mike, Great job so far!

There is a horizontal scroll that you can fix with :
> body {
  max-width: 100%;
  overflow-x: hidden;
}

When the screen size is small the background image goes over the text and decreases the readability.  You could use, so when the screen gets smaller background image also does.
> background-size: calc(25% + 100px);

**Comment by mrEckendonk** [comment]
issue fixed here ; 3a1c8630be592936a3410cfaad33b2f23bc97422
