### ISSUE TITLE
Button Weight and social color change

### ISSUE THREAD

**Issue by Nizamuddin4493** [mrEckendonk/portfolio#4]
Hi Mike.
You did your job very great :clap:  It is nice but you have to make some changes like social icon color is deemed as compared to Template.
yours
![socials](https://user-images.githubusercontent.com/78977308/140529560-e323442f-b8ec-46c7-9218-74224bdf9cc1.png)
 
Templete
![Untitled2](https://user-images.githubusercontent.com/78977308/140529649-8a5d31d2-fbb4-48d1-90bc-bb691a913ad4.png)

and button weight according to the template is 700 and yours 900, It makes a letter of the button too bold.

**Comment by mrEckendonk** [comment]
# Hi :wave: @Nizamuddin4493 

- [x] Issue 4 can be marked as resolved, replaced logos of social media 

![image](https://user-images.githubusercontent.com/30936842/140550311-64c93679-970f-477e-abc4-4bd5d040fe67.png)
