### ISSUE TITLE
[Enhancements] Portfolio: P2P - CR - 11/11/21

### ISSUE THREAD

**Issue by OmarRamoun** [mrEckendonk/portfolio#9]
# Suggested Enhancements ♻️ 

- [x] 1️⃣ ➕ It would be better if you don't repeat the same commit messages on multiple commits because that would flood the commit history with redundant messages that will increase frustration during a code history review. 🔁 
- [x] 2️⃣ ➕ I believe using commit messages in an Imperative form (and sticking with it for consistency) would be better for a more clear and descriptive messages. ⌚

**Comment by mrEckendonk** [comment]
Thanks for the sugestion. My next commits will be more readable and clean.
